[package]
name = "seda-tally-vm"
version.workspace = true
edition = "2021"
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
seda-wasm-vm = { workspace = true }
seda-runtime-sdk = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing.workspace = true
wasmer = { workspace = true }

[build-dependencies]
cbindgen.workspace = true
